In [1]:
import numpy as np

import py_utils.array_data as array_data

'ArithmeticError'

In [2]:
arr = array_data.TimePoseSequence(10)
arr

<TimePoseSequence contains 10 rows>

---
Timestamps

In [3]:
# unit: nanosecond
# 3600 * 1e9 nanoseconds -> 1 hour
arr.timestamps = np.arange(10) * 3600 * 1e9
arr.timestamps

array([             0,  3600000000000,  7200000000000, 10800000000000,
       14400000000000, 18000000000000, 21600000000000, 25200000000000,
       28800000000000, 32400000000000])

In [4]:
arr.datetime

DatetimeIndex(['1970-01-01 00:00:00', '1970-01-01 01:00:00',
               '1970-01-01 02:00:00', '1970-01-01 03:00:00',
               '1970-01-01 04:00:00', '1970-01-01 05:00:00',
               '1970-01-01 06:00:00', '1970-01-01 07:00:00',
               '1970-01-01 08:00:00', '1970-01-01 09:00:00'],
              dtype='datetime64[ns]', freq=None)

---
Pose

In [5]:
arr.xyz = np.arange(30).reshape(10, 3)
arr.xyz

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [6]:
arr.quaternion = np.vstack(
    [
        np.random.rand(10),  # x
        np.random.rand(10),  # y
        np.random.rand(10),  # z
        np.ones(10),  # W
    ]
).T

In [7]:
arr.quaternion

array([[0.72786191, 0.79559704, 0.85754927, 1.        ],
       [0.98852555, 0.15198057, 0.60553464, 1.        ],
       [0.57877275, 0.55511337, 0.60972209, 1.        ],
       [0.22326183, 0.67220113, 0.77170209, 1.        ],
       [0.6374978 , 0.30476258, 0.0566788 , 1.        ],
       [0.42707619, 0.11127575, 0.47188535, 1.        ],
       [0.70315328, 0.27301257, 0.96714968, 1.        ],
       [0.41128024, 0.76254848, 0.67097259, 1.        ],
       [0.88338814, 0.53707487, 0.0258616 , 1.        ],
       [0.77633679, 0.66122523, 0.0144332 , 1.        ]])

In [8]:
arr.R.shape, arr.R

((10, 3, 3),
 array([[[ 0.05569679, -0.19216717,  0.97978041],
         [ 0.99141512,  0.12690895, -0.03146716],
         [-0.11829594,  0.97312173,  0.19758586]],
 
        [[ 0.6706565 , -0.38471229,  0.63420525],
         [ 0.63860271, -0.13551467, -0.75751063],
         [ 0.37736777,  0.91303462,  0.15479452]],
 
        [[ 0.32511258, -0.28630608,  0.90129387],
         [ 0.92412656,  0.29848378, -0.23853202],
         [-0.20072843,  0.91045937,  0.36162389]],
 
        [[ 0.00117649, -0.59280758,  0.80534327],
         [ 0.87904659,  0.38454847,  0.28177929],
         [-0.47673442,  0.70760275,  0.5215579 ]],
 
        [[ 0.87208923,  0.18317075,  0.4537718 ],
         [ 0.33406312,  0.45475278, -0.82559176],
         [-0.35757825,  0.8715781 ,  0.33539441]],
 
        [[ 0.6683372 , -0.59876749,  0.4413648 ],
         [ 0.73287634,  0.42845358, -0.52850715],
         [ 0.12734857,  0.6766868 ,  0.72517399]],
 
        [[ 0.19346829, -0.61906957,  0.76113264],
         [ 0.925688

---
Indexing

In [9]:
arr.datetime

DatetimeIndex(['1970-01-01 00:00:00', '1970-01-01 01:00:00',
               '1970-01-01 02:00:00', '1970-01-01 03:00:00',
               '1970-01-01 04:00:00', '1970-01-01 05:00:00',
               '1970-01-01 06:00:00', '1970-01-01 07:00:00',
               '1970-01-01 08:00:00', '1970-01-01 09:00:00'],
              dtype='datetime64[ns]', freq=None)

In [10]:
foo = arr[:4]
foo, foo.datetime, foo.xyz

(<TimePoseSequence contains 4 rows>,
 DatetimeIndex(['1970-01-01 00:00:00', '1970-01-01 01:00:00',
                '1970-01-01 02:00:00', '1970-01-01 03:00:00'],
               dtype='datetime64[ns]', freq=None),
 array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]))

In [11]:
foo = arr[[1, 3, 7]]
foo, foo.datetime, foo.xyz

(<TimePoseSequence contains 3 rows>,
 DatetimeIndex(['1970-01-01 01:00:00', '1970-01-01 03:00:00',
                '1970-01-01 07:00:00'],
               dtype='datetime64[ns]', freq=None),
 array([[ 3,  4,  5],
        [ 9, 10, 11],
        [21, 22, 23]]))

In [12]:
foo.index

array([1, 3, 7])